### ISSUE TITLE
How to make Pie chart start at 90 degrees

### ISSUE THREAD

**Issue by ibering** [bkuzmic/raphael-charts-plugin#2]
Hi, thanks for this awesome plugin.

How I could change the pie chart library to start from 90 degrees ?

![pieChart3d](https://user-images.githubusercontent.com/9592910/67104787-dec8d380-f1c7-11e9-83a4-e3870e15527b.png)

Thanks
Irina

**Comment by bkuzmic** [comment]
Hi Irina,
Sorry, but with current code there is no option to change the start position.

**Comment by ibering** [comment]
Hi,

Ah, too bad. Thanks anyway though. 

Best regards
Irina
